//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBO.Hub.DAO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hana {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hana() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBO.Hub.DAO.Resources.Hana", typeof(Hana).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;FieldID&quot; FROM CUFD WHERE &quot;TableID&quot; = &apos;{0}&apos; AND &quot;AliasID&quot; = &apos;{1}&apos;;.
        /// </summary>
        internal static string UserField_Get {
            get {
                return ResourceManager.GetString("UserField_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *  FROM CUFD  WHERE &quot;TableID&quot; = &apos;{0}&apos;;.
        /// </summary>
        internal static string UserField_GetByTable {
            get {
                return ResourceManager.GetString("UserField_GetByTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;KeyId&quot;  FROM OUKD  WHERE &quot;TableName&quot; = &apos;{0}&apos; AND &quot;KeyName&quot; = &apos;{1}&apos;;.
        /// </summary>
        internal static string UserField_GetKey {
            get {
                return ResourceManager.GetString("UserField_GetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT UFD1.&quot;IndexID&quot; 
        ///FROM CUFD 
        ///    INNER JOIN UFD1 ON CUFD.&quot;TableID&quot; = UFD1.&quot;TableID&quot; AND CUFD.&quot;FieldID&quot; = UFD1.&quot;FieldID&quot; 
        ///WHERE CUFD.&quot;TableID&quot; = &apos;{0}&apos; AND CUFD.&quot;AliasID&quot; = &apos;{1}&apos; AND UFD1.&quot;FldValue&quot; = &apos;{2}&apos;;.
        /// </summary>
        internal static string UserField_GetValidValues {
            get {
                return ResourceManager.GetString("UserField_GetValidValues", resourceCulture);
            }
        }
    }
}
